language: ruby

rvm:
  - ruby-head
  - 2.5
  - 2.4
  - 2.3
  - rbx
  - jruby

sudo: false
dist: trusty

script: "bundle exec rake $TASK"

after_success:
  - bundle exec codeclimate-test-reporter

env:
  global:
    # travis encrypt CODECLIMATE_REPO_TOKEN=???
    - secure: "a7sD9iwPJJn3Fj+mn62GAmy/PEguh3elrilsp1KS+WfDiCiIKD8Q5KG2Jv67DGcQAGI3dPWeh7+ZhZ/W7nEipwWUBmSvGYVeoF63y8j6mNRLeekqspj94l47hXyFePj9bCadY1b1/xY4lE1pMEU8eA8AOUHUqCSuH+Kk/MuvyLM="
  matrix:
    - "TASK=test:core_and_plugins TILT=master"
    - "TASK=test:rails RAILS=master"
    - "TASK=test:sinatra SINATRA=master"
    - "TASK=bench"
    - "TASK=bench slow=1"

matrix:
  exclude:
    - rvm: rbx
      env: "TASK=test:rails RAILS=master"
    - rvm: jruby
      env: "TASK=test:rails RAILS=master"
  allow_failures:
    - env: "TASK=test:core_and_plugins TILT=master"
    - env: "TASK=test:rails RAILS=master"
    - env: "TASK=test:sinatra SINATRA=master"
    - rvm: ruby-head
    - rvm: jruby
    - rvm: rbx

notifications:
  irc: "chat.freenode.net#slim-lang"
